[package]
name = "cat_puzzle_rs"
version = "0.1.0"
authors = ["Mercadud <daaboulmarc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"